services:
  - type: web
    name: ai-tools-hub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_tools_hub.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ai-tools-hub.onrender.com
