# Generated by Django 5.2.3 on 2025-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
